services:
  db:
    image: postgres:17
    container_name: slicer_db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - slicer_net
      
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    env_file: mailserver.env
    hostname: mail
    domainname: slicerconnect.from-delhi.net
    ports:
      - "25:25"
      - "587:587"
      - "993:993"
    volumes:
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./maillogs:/var/log/mail
      - ./config-mail:/tmp/docker-mailserver
      - /etc/letsencrypt:/etc/letsencrypt
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
    networks:          
      - slicer_net    
      
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: slicer_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mailserver
    networks:
      - slicer_net
      
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: slicer_frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - slicer_net
      
volumes:
  postgres_data:
  
networks:
  slicer_net:
    driver: bridge
